version: "3"

services:
  app:
    build:
      context: .
      args:
        - NODE_ENV=development
    container_name: "codeflix-micro-videos-typescript"
    command: "./.docker/start.sh"
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - ./package.json:/home/node/package.json
      - ./package-lock.json:/home/node/package-lock.json
      # this is a workaround to prevent host node_modules from accidently getting mounted in container
      # in case you want to use node/npm both outside container for test/lint etc. and also inside container
      # this will overwrite the default node_modules dir in container so it won't conflict with our
      # /home/node/node_modules location.
      - notused:/home/node/app/node_modules
  db:
    image: arm64v8/mysql:8.0.36
    environment:
      - MYSQL_DATABASE=micro_videos
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql:delegated
    security_opt:
      - seccomp:unconfined

volumes:
  notused:
